### ISSUE TITLE
[FEATURE] Add -n option to composer command

### ISSUE THREAD

**Issue by marcelogalmor** [idealista/php_role#30]
### Description

Add -n option (--no-interactive) to the composer command. (https://github.com/idealista/php_role/blob/master/tasks/composer.yml#L4)

### Why is this needed?

If the composer command is executed with root privileges, it remains waiting for confirmation.

### Additional Information

`Continue as root/super user [yes]? `

**Comment by devnix** [comment]
Already implemented in #29
